import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { useSession, signIn, signOut } from 'next-auth/react';

const Home: NextPage = () => {
  const session = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Product Log</h1>

        <p className={styles.description}>
          Build and Ship product like a boss.
        </p>

        <div className={styles.grid}>
          {session.data ? (
            <button className={styles.card} onClick={() => signOut()}>
              Sign Out
            </button>
          ) : (
            <button className={styles.card} onClick={() => signIn()}>
              Sign In
            </button>
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
